-- 모임 테이블 생성
CREATE TABLE gatherings (
    gathering_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(100) NOT NULL,
    description VARCHAR2(500) NOT NULL,
    category VARCHAR2(20) NOT NULL,
    max_participants NUMBER(10) NOT NULL,
    current_participants NUMBER(10) DEFAULT 0 NOT NULL,
    address VARCHAR2(200) NOT NULL,
    latitude NUMBER(10,7) NOT NULL,
    longitude NUMBER(10,7) NOT NULL,
    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    creator_id NUMBER(19) NOT NULL,
    CONSTRAINT fk_gatherings_creator FOREIGN KEY (creator_id) REFERENCES users(users_id)
);

-- 모임 참여자 테이블 생성
CREATE TABLE gathering_participants (
    participant_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gathering_id NUMBER(19) NOT NULL,
    user_id NUMBER(19) NOT NULL,
    role VARCHAR2(20) DEFAULT 'MEMBER' NOT NULL,
    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_participants_gathering FOREIGN KEY (gathering_id) REFERENCES gatherings(gathering_id) ON DELETE CASCADE,
    CONSTRAINT fk_participants_user FOREIGN KEY (user_id) REFERENCES users(users_id) ON DELETE CASCADE,
    CONSTRAINT uk_participants_gathering_user UNIQUE (gathering_id, user_id)
);

-- 인덱스 생성
CREATE INDEX idx_gatherings_status ON gatherings(status);
CREATE INDEX idx_gatherings_category ON gatherings(category);
CREATE INDEX idx_gatherings_creator ON gatherings(creator_id);
CREATE INDEX idx_gatherings_location ON gatherings(latitude, longitude);
CREATE INDEX idx_participants_gathering ON gathering_participants(gathering_id);
CREATE INDEX idx_participants_user ON gathering_participants(user_id);

-- 코멘트 추가
COMMENT ON TABLE gatherings IS '모임 정보 테이블';
COMMENT ON TABLE gathering_participants IS '모임 참여자 정보 테이블';

COMMENT ON COLUMN gatherings.gathering_id IS '모임 ID';
COMMENT ON COLUMN gatherings.title IS '모임 제목';
COMMENT ON COLUMN gatherings.description IS '모임 설명';
COMMENT ON COLUMN gatherings.category IS '모임 카테고리';
COMMENT ON COLUMN gatherings.max_participants IS '최대 참여자 수';
COMMENT ON COLUMN gatherings.current_participants IS '현재 참여자 수';
COMMENT ON COLUMN gatherings.address IS '모임 주소';
COMMENT ON COLUMN gatherings.latitude IS '위도';
COMMENT ON COLUMN gatherings.longitude IS '경도';
COMMENT ON COLUMN gatherings.status IS '모임 상태 (ACTIVE, INACTIVE)';
COMMENT ON COLUMN gatherings.created_at IS '생성일시';
COMMENT ON COLUMN gatherings.updated_at IS '수정일시';
COMMENT ON COLUMN gatherings.creator_id IS '생성자 ID';

COMMENT ON COLUMN gathering_participants.participant_id IS '참여자 ID';
COMMENT ON COLUMN gathering_participants.gathering_id IS '모임 ID';
COMMENT ON COLUMN gathering_participants.user_id IS '사용자 ID';
COMMENT ON COLUMN gathering_participants.role IS '참여자 역할 (CREATOR, MEMBER)';
COMMENT ON COLUMN gathering_participants.joined_at IS '참여일시';
