-- Map 관련 테이블 생성 스크립트

-- Locations 테이블
CREATE TABLE LOCATIONS (
    LOCATION_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    ADDRESS VARCHAR2(500) NOT NULL,
    LATITUDE NUMBER NOT NULL,
    LONGITUDE NUMBER NOT NULL,
    IS_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Places 테이블
CREATE TABLE PLACES (
    PLACE_ID NUMBER PRIMARY KEY,
    PLACE_NAME VARCHAR2(200) NOT NULL,
    CATEGORY_NAME VARCHAR2(100),
    ADDRESS_NAME VARCHAR2(500),
    ROAD_ADDRESS_NAME VARCHAR2(500),
    PHONE VARCHAR2(50),
    PLACE_URL VARCHAR2(1000),
    LATITUDE NUMBER NOT NULL,
    LONGITUDE NUMBER NOT NULL,
    KEYWORD VARCHAR2(100),
    IS_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Votes 테이블
CREATE TABLE VOTES (
    VOTE_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    PLACE_URL VARCHAR2(1000) NOT NULL,
    IS_UPVOTE CHAR(1) NOT NULL,
    IS_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UK_USER_PLACE UNIQUE (USER_ID, PLACE_URL)
);

-- 인덱스 생성
CREATE INDEX IDX_LOCATIONS_USER_ID ON LOCATIONS(USER_ID);
CREATE INDEX IDX_LOCATIONS_ACTIVE ON LOCATIONS(IS_ACTIVE);
CREATE INDEX IDX_PLACES_KEYWORD ON PLACES(KEYWORD);
CREATE INDEX IDX_PLACES_ACTIVE ON PLACES(IS_ACTIVE);
CREATE INDEX IDX_PLACES_COORDINATES ON PLACES(LATITUDE, LONGITUDE);
CREATE INDEX IDX_VOTES_PLACE_URL ON VOTES(PLACE_URL);
CREATE INDEX IDX_VOTES_USER_ID ON VOTES(USER_ID);
CREATE INDEX IDX_VOTES_ACTIVE ON VOTES(IS_ACTIVE);
